#!/bin/bash
EnvDir="${PYENVDIR:-$HOME/dev/python/pydevenv}"
if [ $1 ]; then
    poetry new $1 > /dev/null
    cd $1
    poetry add ipython pysnooper flake8 black pytest pytest-cov --group dev > /dev/null
    git init > /dev/null
    gh auth login --with-token < $EnvDir/pat.txt
    cp $EnvDir/pytest.ini .
    cp $EnvDir/.flake8 .
    mkdir .vscode
    cp $EnvDir/settings.json .vscode/
    cp $EnvDir/launch.json .vscode/
    git add .
    git commit -m "Initial commit" > /dev/null
    git branch -M main > /dev/null
    gh repo create $1 --public --push --source=. > /dev/null 2> /dev/null
fi
