#!/bin/bash
cols=$(tput cols)

if [[ $1 == "-h" || $1 == "--help" ]]
then
    directions="""Usage: pydevenv project_folder

Description: Sets up an initial Python project directory with tooling, adds it to a Git repo, and pushes it to GitHub.

Prerequisites:
- Poetry (https://python-poetry.org)
- GitHub CLI (https://cli.github.com)
- A \$PYDEVENV environment variable with a path to your local pydevenv folder.
- A pat.txt file in the pydevenv folder containing your GitHub Personal Access Token. Your PAT must have permissions to create a repo, commit files and push them to GitHub.\n
"""
    printf "${directions}" | fold -w $cols -s
    exit 0;
elif [[ -z ${PYDEVENV} ]]
then
   directions="Please define \$PYDEVENV to point to your pydevenv folder. (e.g., /home/username/pydevenv)\n"
   printf "${directions}" | fold -w $cols -s
   exit 1;
elif [[ ! -f ${PYDEVENV}/pat.txt ]]
then
   directions="Cannot find pat.txt (copy of your GitHub Personal Access Token) inside ${PYDEVENV}. Please check to see that the file exists.\n"
   printf "${directions}" | fold -w $cols -s
   exit 1;
elif [[ -z ${1} ]]
then
    echo "usage: pydevenv project_folder"
    exit 1;
else 
    if [[ $1 == "-v" || $1 == "--VERBOSE" ]]; then
       VERBOSE=1
       PROJ_NAME=$2
    else
       VERBOSE=0
       PROJ_NAME=$1
    fi
    if [[ $VERBOSE -eq 1 ]] || [[ -f ${PYDEVENV}/runonce.txt ]]; then
       exec &> /dev/null
    fi
    env_dir="${PYDEVENV}"
    poetry config virtualenvs.in-project true
    poetry config virtualenvs.prefer-active-python true
    poetry new $PROJ_NAME --name core
    cd $PROJ_NAME
    poetry add ipython pysnooper flake8 yapf pytest pytest-cov --group dev
    git init
    gh auth login --with-token < $env_dir/pat.txt
    cp $env_dir/.gitignore .
    cp $env_dir/pytest.ini .
    cp $env_dir/.flake8 .
    mkdir .vscode 
    cp $env_dir/settings.json .vscode/
    cp $env_dir/launch.json .vscode/
    git add .
    git commit -m "Initial commit"
    git branch -M main
    gh repo create $PROJ_NAME --public --push --source=. 
    touch $env_dir/runonce.txt ;
fi
